### ISSUE TITLE
rename backup file extension from .key to .asc

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2071]
Here

```js
  const asBackupFile = (acctEmail: string, armoredKey: string) => {
    return new Att({ name: `flowcrypt-backup-${acctEmail.replace(/[^A-Za-z0-9]+/g, '')}.key`, type: 'text/plain', data: Buf.fromUtfStr(armoredKey) });
  };
```

---------------------------

Prerequisites - Tom has already checked this, so it's unblocked:

Check on all platforms that it can recognize `.asc` files first:
 - [x] web extension - issue #2342
 - [x] Android App - issue https://github.com/FlowCrypt/flowcrypt-android/issues/792
 - [x] iOS App - issue https://github.com/FlowCrypt/flowcrypt-ios/issues/161

**Comment by tomholub** [comment]
Also use `application/pgp-keys` for mime type

**Comment by tomholub** [comment]
This is because people keep opening it in keynote or something, then getting confused.
