### ISSUE TITLE
don't render meta attachments

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2195]
- [x] rich text: `noname`
- [x] rich text: `encrypted.asc`
- [x] rich text: `signature.asc`
- [x] also attached public keys

![image](https://user-images.githubusercontent.com/6306961/69423526-3eae1f00-0d1e-11ea-87e1-41f5d659ba78.png)
