### ISSUE TITLE
Dedicated keys screen

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2528]
There are several related issues that will become easier if we redesign keys ux and ui.
 - [ ] change pass phrase of all keys #956 
 - [ ] backup several/all keys #2482
 - [ ] replacing primary key with another one #409 

The result should be that "keys" should not just be a small frame, but should have it's own page with a lot more screen space, allowing to add more actions/buttons there.

But have to think about it a bit more first.

Other related issues:
 - [ ] clearer key screen userids  #2547

**Comment by tomholub** [comment]
For now, as we add functionality, we can just make current keys frame bigger - gradually without redoing it completely. If it does become too big, we can pull it aside into its own page.
