### ISSUE TITLE
user self-service

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2869]
Stuff that will decrease load on support and make users happier.

 - [ ] better guidance when forgot pass phrase #681 (many emails about this)
 - [x] improve uninstall feedback https://github.com/FlowCrypt/flowcrypt-web/issues/188
 - [x] a way to delete account
 - [ ] a way to cancel subscription https://github.com/FlowCrypt/flowcrypt-account/issues/24
 - [ ] a way to update payment info for subscription https://github.com/FlowCrypt/flowcrypt-account/issues/25
 - [ ] a way to render invoices https://github.com/FlowCrypt/flowcrypt-account/issues/26

**Comment by seisvelas** [comment]
The Stripe API looks straightforward and the docs are very pleasant, https://stripe.com/docs/api.

Cancellation (https://github.com/FlowCrypt/flowcrypt-account/issues/24), for example, is as easy as:

```javascript
const stripe = require('stripe')('[API_KEY');
const customer = const customers = await stripe.customers.list({
  email: "[CUSTOMER_EMAIL_ADDRESS]",
});
const deleted = await stripe.subscriptions.del(
  customer.data.id
);
```

The Stripe API even gives us a separate testing key so we don't make any dangerous mistakes while developing this feature (and obviously, useful for tests themselves!). More info: https://stripe.com/docs/keys#test-live-modes

As I have access to Stripe I checked to see if I could use our test API key to experiment with this, but unfortunately that feature is disabled for me:

![Screenshot from 2020-10-25 00-07-49](https://user-images.githubusercontent.com/44826516/97101870-1f222380-165e-11eb-9f26-8d26507ee0ab.png)

Stripe's API seems very pleasant and straightforward with very usable docs. I imagine we'd implement the actual Stripe API interactions via endpoints on flowcrypt-backend, and the various features for flowcrypt-account and flowcrypt-browser would just call that. 

I also notice this is marked First Priority. Is there something that makes this more complicated than it first appears, or something blocking this?

**Comment by tomholub** [comment]
Always focus on security issues first if there are any.

Have a look at unix users reading each other's stuff.
