### ISSUE TITLE
OrgRule PASS_PHRASE_CHOSEN_BY_USER

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3596]
In enterprise settings with EKM integration, FlowCrypt client retrieves private key decrypted from EKM (not pass phrase protected). Currently, the client requires that when `PRV_AUTOIMPORT_OR_AUTOGEN` OrgRule is used (meaning - pull keys from EKM during setup), that `PASS_PHRASE_QUIET_AUTOGEN` is also used together with it. This combination together created and stored pass phrase silently, this procedure can be seen in `setupWithEkmThenRenderSetupDone`.

We need a new OrgRule `PASS_PHRASE_CHOSEN_BY_USER` which will prompt the enterprise user to enter their own pass phrase during the setup when pulling keys from EKM.

Applicability and restrictions of `PASS_PHRASE_CHOSEN_BY_USER`:
 - only meaningful when combined with: `PRV_AUTOIMPORT_OR_AUTOGEN`. 
 - conflicts with `PASS_PHRASE_QUIET_AUTOGEN` (cannot be set simultaneously)

**Todo on docs repo:**
 - [ ] update https://flowcrypt.com/docs/business/org-rules.html

**Todo on browser repo:**
 - [x] (tom) meaningfuly refactor / classes / methods in a separate PR  #3670
 - [ ] update OrgRules class to understand this new rule, including restrictions. Add method `OrgRules.userMustChoosePassPhraseDuringPrvAutoimport()`. When the method is called:
       - check if `PASS_PHRASE_CHOSEN_BY_USER` present
       - if present, throw if  `PRV_AUTOIMPORT_OR_AUTOGEN` is **not** set at the same time
       - if present, throw if `PASS_PHRASE_QUIET_AUTOGEN` is set
       - return boolean
 - [ ] use this OrgRule during import when pulling from EKM in `setupWithEkmThenRenderSetupDone` to decide which flow to follow
 - [ ] reuse parts of `step_2a_manual_create` - just the `Choose pass phrase to protect your encrypted emails. choosing secure pass phrases` and two pass phrase fields and a button now called `continue` instead of `create and save`, to make a new block called `step_2_ekm_choose_pass_phrase`
 - [ ] connect the UI elements to pass phrase strength evaluation with `initPassphraseToggle`
 - [ ] add UI tests for this combination of OrgRules + this setup flow

part of https://github.com/FlowCrypt/flowcrypt-browser/issues/2125

**Comment by tomholub** [comment]
For now, the chosen pass phrase will be stored locally along with the private key, just like before. A followup issue #2752 will optionally change that

**Comment by rrrooommmaaa** [comment]
Is `PASS_PHRASE_CHOSEN_BY_USER` just the opposite of `PASS_PHRASE_QUIET_AUTOGEN`.
Is there a reason why we can't have this behaviour when `PRV_AUTOIMPORT_OR_AUTOGEN` is set and `PASS_PHRASE_QUIET_AUTOGEN` is unset?

**Comment by tomholub** [comment]
> Is PASS_PHRASE_CHOSEN_BY_USER just the opposite of PASS_PHRASE_QUIET_AUTOGEN.

Yes, it's mutually exclusive.

> Is there a reason why we can't have this behaviour when PRV_AUTOIMPORT_OR_AUTOGEN is set and PASS_PHRASE_QUIET_AUTOGEN is unset?

I guess you're right. It's more explicit to use the OrgRule, but really, it could just be made the opposite.

While I already told the customer we will be implementing it with a special OrgRule, I don't think they care exactly how we do it.
