### ISSUE TITLE
use FES to upload password protected messages when available

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3672]
part of #2125 

- [x] remove unused API calls `messageExpiration` and `messageLink` https://github.com/FlowCrypt/flowcrypt-browser/pull/3673
- [x] remove unused API path `message/expiration` on backend https://github.com/FlowCrypt/flowcrypt-backend/issues/370
- [x] stop saving `admin_code` https://github.com/FlowCrypt/flowcrypt-browser/pull/3673
- [x] update code to stop using `short` instead use `url` response from backend https://github.com/FlowCrypt/flowcrypt-browser/pull/3673
- [x] design `message/upload` and `message/reply-token` on FES https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/issues/1269
- [ ] update following two methods to use FES when available. FES API is at https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/issues/1269

```
  public messageUpload = async (fcAuth: FcUuidAuth | undefined, encryptedDataBinary: Uint8Array, progressCb: ProgressCb): Promise<BackendRes.FcMsgUpload> => {
    return await FlowCryptComApi.messageUpload(fcAuth, encryptedDataBinary, progressCb);
  }

  public messageToken = async (fcAuth: FcUuidAuth): Promise<BackendRes.FcMsgToken> => {
    return await FlowCryptComApi.messageToken(fcAuth);
  }
```
