### ISSUE TITLE
priorities - browser

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4108]
- [x] (limonte) security - adding warning when importing public keys - #4097 
 - [x] (limonte) End user Passphrase management (remove post-it note prompt) #4080 
 - [x] (limonte) Secure Reply button is doing a "reply all" instead of just replying to the one recipient #4077 
 - [x] (limonte+tom) People API #4106 
 - [x] Secure Compose button in "New Gmail view" not good #4099 
 - [x] Logo of "Secure Compose" in "Gmail normal view" not appearing #4098 
 - [x] #4251
